// Code generated by "stringer -type=CardType -trimprefix=Card"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CardAttack-0]
	_ = x[CardMagicArrow-1]
	_ = x[CardRetreat-2]
	_ = x[CardRest-3]
	_ = x[CardPowerAttack-4]
	_ = x[CardFirebolt-5]
	_ = x[CardStun-6]
	_ = x[CardHeal-7]
	_ = x[CardParry-8]
}

const _CardType_name = "AttackMagicArrowRetreatRestPowerAttackFireboltStunHealParry"

var _CardType_index = [...]uint8{0, 6, 16, 23, 27, 38, 46, 50, 54, 59}

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardType_index)-1) {
		return "CardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardType_name[_CardType_index[i]:_CardType_index[i+1]]
}
